Foros_ORT/Foros_ORT/Models/Posteo.cs
using System;
using System.Collections.Generic;

namespace Foros_ORT.Models
{
    public class Posteo
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public DateTime Creado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Foro Foro { get; set; }
        public virtual IEnumerable<Respuesta> Respuestas { get; set; }
    }
}

Foros_ORT/Foros_ORT/Controllers/ForoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foros_ORT.Models;
using Foros_ORT.Models.ModelosForo;
using Foros_ORT.Models.ModelosPosteo;
using Microsoft.AspNetCore.Mvc;

namespace Foros_ORT.Controllers
{
    public class ForoController : Controller
    {
        private readonly IPosteo _servicioPosteo;
        private readonly IForo _servicioForo;
        public ForoController(IForo servicioForo, IPosteo servicioPosteo)
        {
            _servicioForo = servicioForo;
            _servicioPosteo = servicioPosteo;
        }
        public IActionResult Index()
        {
            var foros = _servicioForo.ObtenerTodos()
                .Select(foro => new ModeloListadoForo
            {
                    Id = foro.Id,
                    Nombre = foro.Titulo,
                    Descripcion = foro.Descripcion,
                    UrlImagen = foro.UrlImagen
                    
            }
            );
            var model = new ModeloIndiceForo
            {
                ListaForo = foros
            };
            return View(model);
        }
        
        public IActionResult Tema(int id, string PedidoBusqueda)
        {
            var foro = _servicioForo.ObtenerPorId(id);
            var posteos = new List<Posteo>();

            posteos = _servicioPosteo.ObtenerPosteosFiltrados(foro, PedidoBusqueda).ToList();

            var listadoPosteo = posteos.Select(posteo => new ModeloListadoPosteo
            {
                Id = posteo.Id,
                Titulo = posteo.Titulo, 
                IdAutor = posteo.Usuario.Id,
                NombreAutor = posteo.Usuario.UserName,
                CantidadRespuestas = posteo.Respuestas.Count(),
                Fecha = posteo.Creado.ToString(),
                Foro = PasarForoAModeloListadoForo(posteo)
            }
            );
            
            var model = new ModeloTemaForo
            {
                Posteos = listadoPosteo,
                Foro = PasarForoAModeloListadoForo(foro)
            };
            
            return View(model);
        }
        
        private ModeloListadoForo PasarForoAModeloListadoForo(Posteo posteo)
        {
            var foro = posteo.Foro;
            return PasarForoAModeloListadoForo(foro);
        }

        private ModeloListadoForo PasarForoAModeloListadoForo(Foro foro)
        {
            return new ModeloListadoForo
            {
                Id = foro.Id,
                Nombre = foro.Titulo,
                Descripcion = foro.Descripcion,
                UrlImagen = foro.UrlImagen
            };
        }
        
        [HttpPost]
        public IActionResult Buscar(int id, string PedidoBusqueda)
        {
            return RedirectToAction("Tema", new { id, PedidoBusqueda });
        }
    }
}
 

Foros_ORT/Foros_ORT/Controllers/PosteoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foros_ORT.Models;
using Foros_ORT.Models.ModelosPosteo;
using Foros_ORT.Models.ModelosRespuesta;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Foros_ORT.Controllers
{
    public class PosteoController : Controller
    {
        private readonly IForo _servicioForo;
        private readonly IPosteo _servicioPosteo;
        private static UserManager<Usuario> _administradorUsuario;
        public PosteoController(IPosteo servicioPosteo, IForo servicioForo, UserManager<Usuario> administradorUsuario)
        {
            _servicioPosteo = servicioPosteo;
            _servicioForo = servicioForo;
            _administradorUsuario = administradorUsuario;
        }
        public IActionResult Index(int id)
        {
            var posteo = _servicioPosteo.ObtenerPorId(id);
            var respuestas = ArmarRespuestas(posteo.Respuestas);
            var model = new ModeloIndicePosteo
            {
                Id = posteo.Id,
                Titulo = posteo.Titulo,
                IdAutor = posteo.Usuario.Id,
                nombreAutor = posteo.Usuario.UserName,
                UrlImagenAutor = posteo.Usuario.UrlImagen,
                Creado = posteo.Creado,
                Contenido = posteo.Contenido,
                Respuestas = respuestas,
                IdForo = posteo.Foro.Id,
                NombreForo = posteo.Foro.Titulo
            };
            return View(model);
        }
        public IActionResult Crear(int id)
        {
            var foro = _servicioForo.ObtenerPorId(id);
            var model = new ModeloNuevoPosteo
            {
                NombreForo = foro.Titulo,
                IdForo = foro.Id,
                UrlImagenForo = foro.UrlImagen,
                NombreAutor = User.Identity.Name
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AgregarPosteo(ModeloNuevoPosteo model)
        {
            var idUsuario = _administradorUsuario.GetUserId(User);
            var usuario = await _administradorUsuario.FindByIdAsync(idUsuario);
            var posteo = armarPosteo(model, usuario);

             _servicioPosteo.Agregar(posteo).Wait();
            return RedirectToAction("Index", "Posteo", new { id = posteo.Id });
        }

        private Posteo armarPosteo(ModeloNuevoPosteo model, Usuario usuario)
        {
            var foro = _servicioForo.ObtenerPorId(model.IdForo);
            return new Posteo
            {
                Titulo = model.Titulo,
                Creado = DateTime.Now,
                Contenido = model.Contenido,
                Usuario = usuario,
                Foro = foro
            };
        }
        private IEnumerable<ModeloRespuestaPosteo> ArmarRespuestas(IEnumerable<Models.Respuesta> respuestas)
        {
            return respuestas.Select
            (r => new ModeloRespuestaPosteo
            {
                Id = r.Id,
                NombreAutor = r.Usuario.UserName,
                IdAutor = r.Usuario.Id,
                UrlImagenAutor = r.Usuario.UrlImagen,
                Creado = r.Creado,
                Contenido = r.Contenido
            }
            );
        }
        public IActionResult Editar(int id, int idForo)
        {
            var foro = _servicioForo.ObtenerPorId(idForo);
            var posteo = _servicioPosteo.ObtenerPorId(id);
            ViewData["idPosteo"] = id;
            var model = new ModeloNuevoPosteo
            {
                NombreForo = foro.Titulo,
                IdForo = foro.Id,
                UrlImagenForo = foro.UrlImagen,
                NombreAutor = User.Identity.Name,
                Contenido = posteo.Contenido,
                Titulo = posteo.Titulo
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditarPosteo(ModeloNuevoPosteo model, int idPosteo)
        {
            _servicioPosteo.EditarTituloPosteo(idPosteo, model.Titulo).Wait();
            _servicioPosteo.EditarContenidoPosteo(idPosteo, model.Contenido).Wait();
            return RedirectToAction("Index", "Posteo", new { id = idPosteo });
        }
    }
}

Foros_ORT/Foros_ORT/Controllers/RespuestaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foros_ORT.Models;
using Foros_ORT.Models.ModelosRespuesta;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Foros_ORT.Controllers
{
    public class RespuestaController : Controller
    {
        private readonly UserManager<Usuario> _administradorUsuario;
        private readonly IPosteo _servicioPosteo;
        public RespuestaController(IPosteo servicioPosteo, UserManager<Usuario> administradorUsuario)
        {
            _servicioPosteo = servicioPosteo;
            _administradorUsuario = administradorUsuario;
        }
        public async Task<IActionResult> Crear(int id)
        {
            var posteo = _servicioPosteo.ObtenerPorId(id);
            var usuario = await _administradorUsuario.FindByNameAsync(User.Identity.Name);

            var model = new ModeloRespuestaPosteo
            {
                ContenidoPosteo = posteo.Contenido,
                TituloPosteo = posteo.Titulo,
                IdPosteo = posteo.Id,
                NombreAutor = User.Identity.Name,
                IdAutor = usuario.Id,
                Creado = DateTime.Now,
                NombreForo = posteo.Foro.Titulo,
                IdForo = posteo.Foro.Id
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AgregarRespuesta(ModeloRespuestaPosteo model)
        {
            var idUsuario = _administradorUsuario.GetUserId(User);
            var usuario = await _administradorUsuario.FindByIdAsync(idUsuario);

            var respuesta = ArmarRespuesta(model, usuario);

            await _servicioPosteo.AgregarRespuesta(respuesta);

            return RedirectToAction("Index", "Posteo", new { id = model.IdPosteo });
        }

        private Respuesta ArmarRespuesta(ModeloRespuestaPosteo model, Usuario usuario)
        {
            var posteo = _servicioPosteo.ObtenerPorId(model.IdPosteo);

            return new Respuesta
            {
                Posteo = posteo,
                Contenido = model.Contenido,
                Creado = DateTime.Now,
                Usuario = usuario
            };
        }

        public IActionResult Editar(int id, int idPosteo, string contenido)
        {
            var posteo = _servicioPosteo.ObtenerPorId(idPosteo);
            var model = new ModeloRespuestaPosteo
            {
                ContenidoPosteo = posteo.Contenido,
                TituloPosteo = posteo.Titulo,
                IdPosteo = posteo.Id,
                NombreAutor = User.Identity.Name,
                Creado = DateTime.Now,
                NombreForo = posteo.Foro.Titulo,
                IdForo = posteo.Foro.Id,
                Contenido = contenido,
                Id = id
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditarRespuesta(ModeloRespuestaPosteo model, int idPosteo)
        {
            _servicioPosteo.EditarRespuesta(model.Id, model.Contenido).Wait();
            return RedirectToAction("Index", "Posteo", new { id = idPosteo });
        }
    }
}

Foros_ORT/Foros_ORT/Views/Posteo/Crear.cshtml
@model Foros_ORT.Models.ModelosPosteo.ModeloNuevoPosteo

<h1>Nuevo Posteo de @Model.NombreForo</h1>

<form asp-action="AgregarPosteo" method="post" id="formularioAgregarPosteo">

    <div class="form-group">
        <label asp-for="Titulo"></label>
        <input asp-for="Titulo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Contenido"></label>
        <input asp-for="Contenido" class="form-control" />
    </div>
    <button type="submit" id="botonSubirPosteo" class="btn btn-outline-dark">
        Subir Posteo
    </button>
    <input asp-for="IdForo" type="hidden" />

</form>

Foros_ORT/Foros_ORT/Views/Posteo/Editar.cshtml
@model Foros_ORT.Models.ModelosPosteo.ModeloNuevoPosteo

<h1>Posteo a editar de @Model.NombreForo</h1>

<form asp-action="EditarPosteo" asp-route-idPosteo="@ViewData["idPosteo"]" method="post" id="formularioAgregarPosteo">

    <div class="form-group">
        <label asp-for="Titulo"></label>
        <input asp-for="Titulo" class="form-control" placeholder="@Model.Titulo" />
    </div>
    <div class="form-group">
        <label asp-for="Contenido"></label>
        <input asp-for="Contenido" class="form-control" placeholder="@Model.Contenido" />
    </div>
    <button type="submit" id="botonSubirPosteo" class="btn btn-outline-dark">
        Editar Posteo
    </button>
    <input asp-for="IdForo" type="hidden" />

</form>

Foros_ORT/Foros_ORT/Views/Posteo/Index.cshtml
@model Foros_ORT.Models.ModelosPosteo.ModeloIndicePosteo

<a asp-controller="Foro" asp-action="Tema" asp-route-id="@Model.IdForo"><h2 class="btn btn-info">Volver al foro @Model.NombreForo</h2></a>

<h1>@Model.Titulo</h1>

@if (User.Identity.Name == Model.nombreAutor)
{
    <a asp-controller="Posteo" asp-action="Editar" asp-route-id="@Model.Id" asp-route-idForo="@Model.IdForo" class="btn btn-primary">Editar</a>
}


@if (User != null)
{
    <a asp-controller="Respuesta" asp-action="Crear" asp-route-id="@Model.Id" class="btn btn-secondary">Responder</a>
}




<div class="container alert-heading" style="background-color:beige; margin-top:15px;">

    <div>
        Autor: @Model.nombreAutor
        <br />
        Creado: @Model.Creado
    </div>
    <hr />
    <div>
        @Model.Contenido
    </div>
</div>
@if (Model.Respuestas.Any())
{
    foreach (var respuesta in Model.Respuestas)
    {
<div class="container alert-info" style="margin-top:15px;">
    @if (respuesta.NombreAutor == User.Identity.Name)
    {
        <a asp-controller="Respuesta" asp-action="Editar"asp-route-id="@respuesta.Id"  asp-route-idPosteo="@Model.Id" asp-route-contenido="@respuesta.Contenido"  class="btn btn-danger">Editar</a>
    }
    <div>
        Autor de la respuesta: @respuesta.NombreAutor
        <br />
        Fecha de la respuesta: @respuesta.Creado
    </div>
    <hr />
    <div>
        @respuesta.Contenido
    </div>
</div>
    }
}
else
{
    <div style="background-color:aqua; margin-top:15px;">
        <h3>Este posteo aún no ha recibido respuestas</h3>
    </div>
}